- clients/fortnite_api.py
- clients/fortnite_tracker.py
- fortnite_bot.py
- requirements.txt
Add a workflow that pulls from FN Tracker
> Add FN Tracker

- clients/fortnite_tracker.py
Added:
• Win count in the Discord message description
• Commas to format numbers
• Clarified TODOs
> Add Wins Description

- .env.example
- clients/fortnite_api.py
- clients/fortnite_tracker.py
- database/mysql
- database/mysql.py
- requirements.txt
Added:
- Track players in database
- Auto-fetch the latest season data when the season changes
> Track Players in Database

- .env.example
- clients/fortnite_tracker.py
- clients/stats.py
- database/mysql.py
- exceptions.py
- fortnite_bot.py
- utils/dates.py
Added:
- Squad tracking
- Other stats tracking framework for the future
> Add Squad Tracking, Framework for Future Stats Tracking

- clients/fortnite_api.py
- clients/fortnite_tracker.py
- clients/stats.py
- database/mysql.py
- fortnite_bot.py
Add:
- !stats diff
- !stats diff \<username\>
**This is a temporarily commit so that the bot can have these features today!**
A follow-up MR will clean-up the code.
> Add Daily Stats Diff Command

- fortnite_bot.py
Fix:
- Remove extra `silent` arg
> Remove Extra Silent Param

- .env.example
- clients/interactions.py
- clients/stats.py
- commands.py
- fortnite_bot.py
Added:
- "Do you want to see current squad stats" question?
- Wait for emoji response
- `interactions.py` file
> Add Track Question on Voice Channel Join

- fortnite_bot.py
Fixed:
- Voice State check. Only output message when a user joins the voice channel.
> Fixed Voice State Check

- fortnite_bot.py
Fixed:
- Voice State logic check.. again
> Fixed Voice State Check Again

- clients/fortnite_tracker.py
- Changed search endpoint to use fortnite tracker's website search url instead of api
- Parsed username from the redirected url
> Fixes username issue in fortnitetracker where the player name is different from what is in fortnitetracker

- utils/discord.py
change skill indicator color to new colors
> Update skill indicator color

- utils/discord.py
Updates:
- Removed `print` dev artifacts
> Remove print dev artifacts

- clients/interactions.py
- fortnite_bot.py
Change "squad player" to only the people who are currently in the voice channel
> Change squad players list to only people who joined voice channel today

- .env.example
- fortnite_bot.py
update change squad players list to only users who joined voice channel, remove once user leaves
> update change squad players list to only people who joined channel

- clients/interactions.py
- fortnite_bot.py
Reverts chao813/Fortnite-Discord-Bot#52
> Revert "remove incorrect logic for removing user from squad player list when user leaves voice channel"

- clients/fortnite_api.py
- clients/interactions.py
- commands.py
- fortnite_bot.py
fix bugs & syntax suggestions from PR #55
> comment out section that causes squad players session list to error

- README.md
Added pip installation ordering issues
> Update README with dependency installation instructions

- README.md
Update readme for executable generation
> Update README to fix pyinstaller instructions

- README.md
Update README with required environmental variables for Replay Watcher generation.
> Update README with replay watcher env vars

- .env.example
- clients/openai.py
- commands.py
- fortnite_bot.py
- requirements.txt
Add:
- New `!ask` command for OpenAI ChatGPT chat completion
> Add ChatGPT chat completion command

- clients/fortnite_api.py
- clients/fortnite_tracker.py
- clients/twitch.py
- exceptions.py
- fortnite_bot.py
- utils/discord.py
Changes:
- Fixed Fortnite API
- Deprecated Fortnite Tracker
> Fixed Fortnite API, deprecated Fortnite Tracker

- clients/fortnite_api.py
Fixed:
- Updated comparison logic of `_is_latest_season`
> Fix latest season ID comparison logic

- clients/fortnite_api.py
- fortnite_bot.py
Fixed:
- Added missing `season_id` flag when making the first player stats search query
> Fixed missing season_id flag

- clients/fortnite_api.py
- clients/interactions.py
- clients/openai.py
- exceptions.py
- fortnite_bot.py
Fixes various bugs related to:
- Fortnite API
- OpenAI
- Discord on join event
> Fix various bugs

- clients/fortnite_api.py
Changes:
- Fix winrate percentage to show correct percentage format
> Fix winrate percentage

- clients/fortnite_api.py
- requirements.txt
- utils/discord.py
Changes:
- Use `account_id` instead of `username` for ranked lookup
- Fixed `UnboundLocalError` if no results were returned from ranked lookup
- Update `requests` to patch security vulnerability
> Fixed player rank lookup

- utils/discord.py
Changes:
- Update KD thresholds
- Refactor URLs
> Update KD thresholds

- clients/fortnite_api.py
- clients/interactions.py
- clients/openai.py
- clients/stats.py
- commands.py
- database/mysql.py
- exceptions.py
- fortnite_bot.py
- utils/discord.py
Changes:
- Misc changes on `rank` operations including tracking ranks in the DB now
- Update `track` to search for all squad members if nobody is on Discord
- Updated maps for hirable NPCs and bunker locations
> Misc changes on rank, track, and maps

- clients/stats.py
- commands.py
- database/mysql.py
- fortnite_bot.py
- utils/discord.py
Changes:
- Removed TRN info from stats outputs
- Combined `!rate` and `!stats played` commands as they're very similar
- Added ranks breakdown to the new `!stats played`
- Fixed issue where `!stats played` was previously grabbing stats for our own squad
> Combine !rate and !stats played

- clients/fortnite_api.py
- fortnite_bot.py
- utils/discord.py
Changes:
- Fixed rank progression to show the correct value
- Added debug logs to check voice channel states
> Fixed rank progression, added voice channel debug logs

- fortnite_bot.py
Changes:
- Removed voice channel debug logs
- Fixed misleading logger message when stats are logged silently
> Removed voice channel debug logs

- .env.example
- .gitignore
- Makefile
- bot/bot.py
- bot/discord_utils.py
- bot/interactions.py
- core/clients/fortnite_api.py
- core/clients/fortnite_tracker.py
- core/config.py
- core/config/config.example.yaml
- core/database/mysql.py
- core/exceptions.py
- core/logger.py
- core/utils/replays.py
- requirements.txt
- scripts/test_player_stats.py
Changes:
- Move configurations away from .env into config.yaml
> Store configurations in config.yaml

- core/clients/fortnite_api.py
Changes:
- Fix bug where `all` mode stats are being excluded
> Fix aggregated stats mode

- core/clients/fortnite_api.py
Changes:
- Fix case where player has no records for game mode
> Return appropriate message for no game records
